import type { Category, Exercise, PlanUnit, RoutineStep } from './types'

const missing = 'Im Trainingsplan nicht angegeben.'

function exercise(
  id: string,
  name: string,
  category: Category,
  goal: string,
  execution = missing,
  mistakes = missing,
  easier = missing,
  harder = missing,
  substitute = missing,
): Exercise {
  return { id, name, category, goal, execution, mistakes, easier, harder, substitute }
}

export const exercises: Exercise[] = [
  exercise('cat-cow', 'Cat-Cow', 'Mobility', 'Basisreiz für die Wirbelsäule', 'Kleiner bis mittlerer Bewegungsradius.', 'Endpositionen erzwingen.', 'Routine bei verspanntem Rücken auf 5–8 Minuten reduzieren.'),
  exercise('hip-switches', '90/90 Hip Switches', 'Mobility', 'Hüftmobilität', 'Kontrolliert ausführen, nicht erzwingen.', 'Die Bewegung erzwingen.'),
  exercise('lunge-stretch', 'Ausfallschritt-Stretch', 'Mobility', 'Hüftbeuger mobilisieren', 'Sanft ausführen, ohne LWS-Überstreckung.', 'LWS überstrecken.', 'Couch Stretch', missing, 'Couch Stretch'),
  exercise('couch-stretch', 'Couch Stretch', 'Mobility', 'Hüftbeuger mobilisieren', 'Sanft ausführen, ohne LWS-Überstreckung.', 'LWS überstrecken.', 'Ausfallschritt-Stretch', missing, 'Ausfallschritt-Stretch'),
  exercise('open-book', 'Open Book', 'Mobility', 'BWS-Rotation zur Entlastung der HWS', 'Die Rotation kommt aus der Brustwirbelsäule.', 'Endpositionen erzwingen.'),
  exercise('chin-tucks', 'Chin Tucks', 'Nacken/HWS', 'Tiefe Nackenmuskulatur und Kopfposition', 'Doppelkinn machen; klein und ruhig, nicht nach unten nicken.', 'Nach unten nicken oder in Schmerz hineinarbeiten.', '5 langsame Wiederholungen in der akuten Phase.', '2 × 8, je 3 Sekunden halten.'),
  exercise('dead-bug', 'Dead Bug', 'Core', 'Rumpfkontrolle; erste Wahl bei LWS-Sensibilität', 'Kontrolliert ausführen.', 'Mit vorgeschobenem Kopf arbeiten.', 'Bird Dog', missing, 'Bird Dog oder Pallof Press'),
  exercise('bird-dog', 'Bird Dog', 'Core', 'Rumpfkontrolle', 'Kontrolliert ausführen.', 'Endpositionen erzwingen.', 'Dead Bug', missing, 'Dead Bug'),
  exercise('head-rotation', 'Kontrollierte Kopfrotation', 'Nacken/HWS', 'Rotation zurückgewinnen, ohne zu forcieren', 'Nur im angenehmen Bereich drehen.', 'Rotation forcieren oder ruckartig dehnen.', 'Kleinere Bewegung in angenehmem Bereich.'),
  exercise('wall-slides', 'Wall Slides', 'Schultern', 'Schulterblattkontrolle und obere Rückenkette', 'Kontrolliert und ruhig ausführen.', 'Schultern hochziehen.'),
  exercise('neck-isometric-side', 'Nacken-Isometrie seitlich', 'Nacken/HWS', 'Belastbarkeit gegen Seitneigung', '3 × 5 Sekunden pro Seite.', 'Ruckartig drücken.'),
  exercise('neck-isometric-front-back', 'Nacken-Isometrie vorne/hinten', 'Nacken/HWS', 'Kontrollierte HWS-Stabilität', 'Vorne und hinten jeweils 3 × 5 Sekunden.', 'Ruckartig drücken.'),
  exercise('bike', 'Bike', 'Beine', 'Lockere Durchblutung und optionales Cardio', 'Locker fahren.', 'Bei gereiztem Rücken oder Knie Vollgas geben.', 'Lockeres Gehen.'),
  exercise('treadmill-walk', 'Laufband-Gehen', 'Beine', 'Lockere Durchblutung', 'Locker gehen.', 'Bei gereiztem Rücken, Knie oder Nacken Joggen erzwingen.', 'Gehen.'),
  exercise('walk', 'Gehen', 'Mobility', 'Durchblutung und Spannung reduzieren', 'Locker 5–15 Minuten gehen.'),
  exercise('knee-to-wall', 'Knie-vor-Wand', 'Knie', 'Sprunggelenksmobilität für bessere Kniekontrolle', 'Sauber und kontrolliert ausführen.', 'Bei Schmerz 4+/10 fortfahren.', 'Bewegungsradius bei Schmerz 3/10 reduzieren.'),
  exercise('tke', 'Terminal Knee Extensions', 'Knie', 'Quadrizeps aktivieren und Endstreckung trainieren', 'Kontrolliert ausführen.'),
  exercise('glute-bridge', 'Glute Bridge', 'Beine', 'Gesäß und Hüfte aktivieren', 'Keine LWS-Überstreckung.', 'LWS überstrecken.', missing, 'Hip Thrust', 'Hip Thrust oder Glute Bridge Maschine'),
  exercise('chest-press', 'Brustpresse', 'Brust', 'Brusttraining', 'Normal bis moderat und sauber; Kopf und Schultern stabil.', 'Kopf oder Schultern instabil werden lassen.', 'Kabel-Brustdrücken', 'Schrägbankdrücken', 'Schrägbankdrücken oder Kabel-Brustdrücken'),
  exercise('incline-press', 'Schrägbankdrücken', 'Brust', 'Brusttraining', 'Normal bis moderat und sauber.', missing, 'Brustpresse', missing, 'Brustpresse'),
  exercise('cable-chest-press', 'Kabel-Brustdrücken', 'Brust', 'Brusttraining', 'Kopf und Schultern stabil halten.', missing, 'Brustpresse', missing, 'Brustpresse'),
  exercise('lat-pulldown', 'Latzug neutral/eng', 'Rücken', 'Rückentraining', 'Neutralen oder engen Griff verwenden.', 'HWS beziehungsweise Schultern hochziehen.'),
  exercise('leg-press', 'Beinpresse beidbeinig', 'Beine', 'Moderater Beinanteil', 'Leicht bis moderat und beidbeinig ausführen.', 'Einbeinige Beinpresse verwenden.', 'Gewicht oder Bewegungsradius reduzieren.', missing, 'Step-ups niedrig'),
  exercise('chest-supported-row', 'Brustgestütztes Rudern', 'Rücken', 'Rücken- und nackenfreundliches Rudern', 'Brustgestützt und kontrolliert rudern.', 'Freies schweres Rudern bei Nackenreiz.', missing, missing, 'Statt freiem Rudern verwenden.'),
  exercise('leg-curl', 'Beinbeuger', 'Beine', 'Ersatz für RDL in der aktuellen Phase', 'Kontrolliert ausführen.', missing, missing, 'RDL erst nach erfolgreichem Re-Entry.', 'RDL-Ersatz zusammen mit Hip Thrust oder Glute Bridge'),
  exercise('lateral-raise', 'Seitheben', 'Schultern', 'Schultertraining', 'Leicht bis moderat, langsam; Schulterblätter kontrollieren.', 'Schwer mit hochgezogenen Schultern ausführen.', 'Leichter und langsamer ausführen.'),
  exercise('biceps-curl', 'Bizepscurls', 'Arme', 'Bizepstraining', 'Kontrolliert ausführen.', missing, 'Hammercurls', missing, 'Hammercurls'),
  exercise('triceps-pushdown', 'Trizeps Pushdowns', 'Arme', 'Trizepstraining', 'Kontrolliert ausführen.', missing, missing, 'Trizepsseil über Kopf bei ruhigem Nacken.', 'Bei Nackenstress statt Überkopf-Trizeps verwenden.'),
  exercise('pallof-press', 'Pallof Press', 'Core', 'Anti-Rotation und Rumpfstabilität', 'Kontrolliert ausführen.', missing, 'Dead Bug', missing, 'Dead Bug'),
  exercise('calf-raise', 'Wadenheben', 'Beine', 'Knie- und Sprunggelenkskette', 'Kontrolliert ausführen.'),
  exercise('hip-flexor-quad-stretch', 'Hüftbeuger-/Quad-Stretch', 'Mobility', 'Sanfter Abschluss', '30–45 Sekunden pro Seite, nur sanft.', 'Dehnung erzwingen.'),
  exercise('monster-walk', 'Monster Walks leicht', 'Beine', 'Beinachse und Hüfte', 'Leicht und kontrolliert ausführen.'),
  exercise('step-up', 'Step-ups niedrig', 'Knie', 'Beintraining mit Priorität für das linke Knie', 'Niedrige Höhe verwenden und langsam ausführen.', 'Zu schnell oder unkontrolliert arbeiten.', 'Bewegungsradius reduzieren.', missing, 'Beidbeinige Beinpresse'),
  exercise('landmine-press', 'Landmine Press', 'Schultern', 'Schultertraining mit reduzierter Nackenbelastung', 'Bei Nackenreiz sehr leicht ausführen oder auslassen.', 'Bei Nackenreiz schwer drücken.', 'Auslassen.', 'Schulterpresse leicht bei ruhigem Nacken.', 'Schulterpresse leicht'),
  exercise('shoulder-press-light', 'Schulterpresse leicht', 'Schultern', 'Schultertraining', 'Nur leicht; bei Nackenreiz auslassen.', 'Schweres Schulterdrücken bei Nackenreiz.', 'Landmine Press sehr leicht oder auslassen.', missing, 'Landmine Press'),
  exercise('hip-thrust', 'Hip Thrust', 'Beine', 'Gesäß und Hüfte trainieren', 'Keine LWS-Überstreckung.', 'LWS überstrecken.', 'Glute Bridge Maschine', missing, 'Glute Bridge Maschine'),
  exercise('glute-bridge-machine', 'Glute Bridge Maschine', 'Beine', 'Gesäß und Hüfte trainieren', 'Keine LWS-Überstreckung.', 'LWS überstrecken.', 'Glute Bridge', 'Hip Thrust', 'Hip Thrust'),
  exercise('reverse-fly', 'Reverse Fly', 'Schultern', 'Hintere Schulter und Schulterblattführung', 'Leicht ausführen und Schulterblätter führen.', 'Schultern hochziehen.', 'Face Pulls', missing, 'Face Pulls'),
  exercise('face-pulls', 'Face Pulls', 'Schultern', 'Schulterblattführung', 'Leicht ausführen und Schulterblätter führen.', 'Schultern hochziehen.', 'Reverse Fly', missing, 'Reverse Fly'),
  exercise('hammer-curl', 'Hammercurls', 'Arme', 'Armtraining', 'Kontrolliert ausführen.', missing, 'Bizepscurls', missing, 'Bizepscurls'),
  exercise('overhead-triceps', 'Trizepsseil über Kopf', 'Arme', 'Trizepstraining', 'Nur verwenden, wenn der Nacken ruhig bleibt.', 'Bei Nackenstress über Kopf trainieren.', 'Trizeps Pushdowns', missing, 'Trizeps Pushdowns'),
  exercise('side-plank', 'Side Plank kurz', 'Core', 'Rumpfstabilität', 'Nur ausführen, wenn der Nacken neutral bleibt.', 'Mit vorgeschobenem Kopf arbeiten.', 'Dead Bug', missing, 'Dead Bug oder Pallof Press'),
  exercise('single-leg-stand', 'Einbeinstand', 'Knie', 'Stabilität und Propriozeption', 'Kontrolliert 30–45 Sekunden pro Seite.', missing, missing, missing, 'Step-down niedrig'),
  exercise('step-down', 'Step-down niedrig', 'Knie', 'Kontrollierte Knieachse', 'Niedrige Höhe und kontrollierte Knieachse.', 'Bei Schmerz 4+/10 fortfahren.', 'Bewegungsradius reduzieren.', 'Step-ups niedrig', 'Step-ups niedrig'),
  exercise('side-bend', 'Seitneigung', 'Nacken/HWS', 'Sanfte Bewegung in der akuten Nackenphase', 'Nur im angenehmen Bereich.', 'Mit der Hand nachziehen.'),
  exercise('shoulder-blades', 'Schulterblätter hinten-unten', 'Nacken/HWS', 'Spannung reduzieren', 'Locker nach hinten-unten bewegen, ohne zu pressen.', 'Pressen oder Schultern hochziehen.'),
  exercise('rdl', 'Rumänisches Kreuzheben', 'Rücken', 'Späterer defensiver Hip-Hinge-Re-Entry', 'Vorerst 2–3 Wochen pausieren. Re-Entry erst, wenn der untere Rücken nach Trainingstagen ruhig bleibt.', 'In der aktuellen Phase normal oder schwer einsteigen.', 'Stufe 1: 2 × 8 sehr leicht mit verkürztem Bewegungsradius.', 'Stufe 3: 2–3 × 8 moderat, nur wenn die LWS 24 Stunden ruhig bleibt.', 'Beinbeuger plus Hip Thrust oder Glute Bridge'),
  exercise('walk-jog', 'Walk/Jog', 'Beine', 'Defensiver Laufaufbau', 'Mit Geh-/Jog-Intervallen der passenden Phase arbeiten.', 'Bei gereiztem Rücken, Knie oder Nacken Joggen erzwingen.', 'Lockeres Gehen oder Bike.'),
]

export const exerciseById = new Map(exercises.map((item) => [item.id, item]))

const step = (exerciseId: string, prescription: string, note: string, targetSets = 1): RoutineStep => ({ exerciseId, prescription, note, targetSets })

export const planUnits: PlanUnit[] = [
  {
    id: 'training-a',
    name: 'Ganzkörpertraining A',
    shortName: 'Training A',
    kind: 'strength',
    description: 'Brust-/Rücken-Fokus mit moderatem Beinanteil, Kniekontrolle und rückenfreundlicher Struktur.',
    frequency: '1× pro Woche',
    steps: [
      step('bike', '5–7 Minuten', 'Locker, nur Durchblutung'),
      step('knee-to-wall', '10 pro Seite', 'Sprunggelenk/Wade für Kniekontrolle'),
      step('tke', '2 × 15 pro Seite', 'Quadrizeps aktivieren', 2),
      step('glute-bridge', '2 × 10', 'Gesäß/Hüfte aktivieren', 2),
      step('chin-tucks', '2 × 8', 'Nackenposition vorbereiten', 2),
      step('chest-press', '3 × 8–10', 'Oder Schrägbankdrücken; normal-moderat, sauber', 3),
      step('lat-pulldown', '3 × 8–10', 'Keine HWS hochziehen', 3),
      step('leg-press', '2–3 × 10–12', 'Leicht-moderat; keine einbeinige Beinpresse', 2),
      step('chest-supported-row', '3 × 10', 'Rücken- und nackenfreundlich', 3),
      step('leg-curl', '2–3 × 10–12', 'Ersatz für RDL in aktueller Phase', 2),
      step('lateral-raise', '2 × 12–15', 'Leicht-moderat; Schultern nicht hochziehen', 2),
      step('biceps-curl', '2 × 10–12', 'Kontrolliert', 2),
      step('triceps-pushdown', '2 × 10–12', 'Kontrolliert', 2),
      step('dead-bug', '2 × 8 pro Seite', 'Erste Wahl bei LWS-Sensibilität', 2),
      step('pallof-press', '2 × 10 pro Seite', 'Anti-Rotation, Rumpfstabilität', 2),
      step('calf-raise', '2 × 15', 'Optional; Knie-/Sprunggelenkskette', 2),
      step('hip-flexor-quad-stretch', '30–45 Sekunden pro Seite', 'Optional; nur sanft'),
    ],
  },
  {
    id: 'training-b',
    name: 'Ganzkörpertraining B',
    shortName: 'Training B',
    kind: 'strength',
    description: 'Schulter-/Arme-/Core-Fokus ohne RDL-Provokation und ohne starke Nackenbelastung.',
    frequency: '1× pro Woche',
    steps: [
      step('bike', '5 Minuten', 'Oder Gehen; locker'),
      step('hip-switches', '6 pro Seite', 'Hüftmobilität'),
      step('wall-slides', '2 × 8', 'Schulterblatt/Nacken', 2),
      step('monster-walk', '2 × 10 Schritte', 'Beinachse/Hüfte', 2),
      step('bird-dog', '2 × 6 pro Seite', 'Rumpfkontrolle', 2),
      step('step-up', '3 × 8 pro Seite', 'Bevorzugt für linkes Knie; langsam', 3),
      step('chest-press', '3 × 8–10', 'Oder Kabel-Brustdrücken; Kopf/Schultern stabil', 3),
      step('chest-supported-row', '3 × 8–10', 'Statt freiem Rudern', 3),
      step('landmine-press', '2 × 8–10', 'Oder Schulterpresse leicht; bei Nackenreiz auslassen oder sehr leicht', 2),
      step('hip-thrust', '2 × 10–12', 'Oder Glute Bridge Maschine; keine LWS-Überstreckung', 2),
      step('reverse-fly', '2 × 12–15', 'Oder Face Pulls; leicht, Schulterblätter führen', 2),
      step('hammer-curl', '2 × 10–12', 'Arme', 2),
      step('triceps-pushdown', '2 × 10–12', 'Oder Trizepsseil über Kopf; bei Nackenreiz Pushdowns', 2),
      step('side-plank', '2 × 20–30 Sekunden pro Seite', 'Nur wenn Nacken neutral bleibt', 2),
      step('dead-bug', '2 × 8 pro Seite', 'Alternative bei Nacken-/LWS-Reiz', 2),
      step('single-leg-stand', '2 × 30–45 Sekunden pro Seite', 'Knie/Propriozeption', 2),
      step('chin-tucks', '2 × 8', 'Ruhig, 2–3 Sekunden halten', 2),
    ],
  },
  {
    id: 'mobility',
    name: 'Tägliche Mobility-Routine',
    shortName: 'Mobility',
    kind: 'routine',
    description: 'Kurzer täglicher Basisreiz für Wirbelsäule, Hüfte, Core und Nacken.',
    frequency: 'Täglich',
    steps: [
      step('cat-cow', '1 Minute', 'Kleiner bis mittlerer Bewegungsradius'),
      step('hip-switches', '2 Minuten', 'Kontrolliert, nicht erzwingen'),
      step('lunge-stretch', '2 Minuten', 'Oder Couch Stretch; sanft, keine LWS-Überstreckung'),
      step('open-book', '1,5 Minuten', 'Rotation aus der Brustwirbelsäule'),
      step('chin-tucks', '1 Minute', 'Doppelkinn, nicht nach unten nicken'),
      step('dead-bug', '2,5 Minuten', 'Oder Bird Dog; nur eine Core-Übung wählen'),
    ],
  },
  {
    id: 'knee',
    name: 'Knie-Routine',
    shortName: 'Knie',
    kind: 'routine',
    description: 'Sprunggelenksmobilität, Quadrizeps, Knieachse und Stabilität.',
    frequency: 'Nach Bedarf / als Prehab',
    steps: [
      step('knee-to-wall', '10 pro Seite', 'Sprunggelenksmobilität'),
      step('tke', '2 × 15 pro Seite', 'Quadrizeps/Endstreckung', 2),
      step('step-down', '2 × 6–8 pro Seite', 'Kontrollierte Knieachse', 2),
      step('single-leg-stand', '30–45 Sekunden pro Seite', 'Stabilität/Propriozeption'),
    ],
  },
  {
    id: 'back',
    name: 'Rücken-Routine',
    shortName: 'Rücken',
    kind: 'routine',
    description: 'Sanfte Elemente aus Mobility und Rückensteuerung; RDL bleibt vorerst pausiert.',
    frequency: 'Bei Bedarf',
    steps: [
      step('cat-cow', '1 Minute', 'Kleiner bis mittlerer Bewegungsradius'),
      step('open-book', '1 × 6 pro Seite', 'BWS-Rotation'),
      step('dead-bug', '2 × 8 pro Seite', 'Erste Wahl bei LWS-Sensibilität', 2),
      step('bird-dog', '2 × 6 pro Seite', 'Rumpfkontrolle', 2),
      step('walk', '5–15 Minuten', 'Durchblutung, Spannung reduzieren'),
    ],
  },
  {
    id: 'neck',
    name: 'Nacken-/HWS-Routine',
    shortName: 'Nacken/HWS',
    kind: 'routine',
    description: 'Sanfter Block für Kopfposition, Rotation, Schulterblattkontrolle und HWS-Stabilität.',
    frequency: '4–6× pro Woche',
    steps: [
      step('chin-tucks', '2 × 8, je 3 Sekunden', 'Tiefe Nackenmuskulatur', 2),
      step('head-rotation', '1 × 6 pro Seite', 'Ohne zu forcieren'),
      step('open-book', '1 × 6 pro Seite', 'BWS-Rotation entlastet HWS'),
      step('wall-slides', '2 × 8', 'Schulterblattkontrolle', 2),
      step('neck-isometric-side', '3 × 5 Sekunden pro Seite', 'Belastbarkeit gegen Seitneigung', 3),
      step('neck-isometric-front-back', 'Je 3 × 5 Sekunden', 'Kontrollierte HWS-Stabilität', 3),
    ],
  },
  {
    id: 'cardio',
    name: 'Cardio / Laufaufbau',
    shortName: 'Cardio',
    kind: 'routine',
    description: 'Defensiver Walk-/Jog-Aufbau oder Bike, nur bei ruhigem Rücken und Knie.',
    frequency: 'Optional 1× pro Woche',
    steps: [
      step('walk-jog', 'Woche 1–2: 5 Min gehen, 1 Min locker joggen, 4 Min gehen – 5 Wiederholungen', 'Nur schmerzfrei wiederholen'),
      step('walk-jog', 'Woche 3–4: 4 Min gehen, 2 Min joggen – 5 Wiederholungen', 'Kein Rücken-/Knieanstieg am Folgetag'),
      step('walk-jog', 'Woche 5–6: 3 Min gehen, 3 Min joggen – 5 Wiederholungen', 'Stabile Technik'),
      step('walk-jog', 'Woche 7–8: 2 Min gehen, 5 Min joggen – 4 Wiederholungen', 'Erst danach Richtung 30 Min durchlaufen'),
    ],
  },
]

export const unitById = new Map(planUnits.map((unit) => [unit.id, unit]))

export const medicalNotice = 'Diese App ersetzt keine ärztliche oder physiotherapeutische Diagnose. Bei starken Schmerzen, Ausstrahlung, Taubheit, Kraftverlust oder deutlicher Verschlechterung sollte medizinisch abgeklärt werden, bevor weitertrainiert wird.'

export const neckWarning = 'Bei starker Bewegungseinschränkung, Ausstrahlung in Arm/Hand, Taubheit, Kraftverlust, Schwindel, Fieber, starken Kopfschmerzen oder Beschwerden nach Unfall: nicht wegtrainieren, sondern medizinisch abklären.'

export const painRules = [
  ['0–2/10', 'Trainieren, aber sauber und kontrolliert.'],
  ['3/10', 'Bewegungsradius oder Gewicht reduzieren.'],
  ['4+/10', 'Übung abbrechen und ersetzen.'],
  ['Schwellung, Wegknicken, Blockieren', 'Training stoppen und medizinisch/physiotherapeutisch abklären.'],
]
