import type { Category, Exercise, PlanUnit, RoutineStep, WorkoutSection } from './types'

const missing = 'Im Trainingsplan nicht angegeben.'

function exercise(
  id: string,
  name: string,
  category: Category,
  goal: string,
  execution = missing,
  mistakes = missing,
  easier = missing,
  harder = missing,
  substitute = missing,
): Exercise {
  return { id, name, category, goal, execution, mistakes, easier, harder, substitute }
}

export const exercises: Exercise[] = [
  exercise('cat-cow', 'Cat-Cow', 'Mobility', 'Basisreiz für die Wirbelsäule', 'Kleiner bis mittlerer Bewegungsradius.', 'Endpositionen erzwingen.', 'Routine bei verspanntem Rücken auf 5–8 Minuten reduzieren.'),
  exercise('hip-switches', '90/90 Hip Switches', 'Mobility', 'Hüftmobilität', 'Kontrolliert ausführen, nicht erzwingen.', 'Die Bewegung erzwingen.'),
  exercise('lunge-stretch', 'Ausfallschritt-Stretch', 'Mobility', 'Hüftbeuger mobilisieren', 'Sanft ausführen, ohne LWS-Überstreckung.', 'LWS überstrecken.', 'Couch Stretch', missing, 'Couch Stretch'),
  exercise('couch-stretch', 'Couch Stretch', 'Mobility', 'Hüftbeuger mobilisieren', 'Sanft ausführen, ohne LWS-Überstreckung.', 'LWS überstrecken.', 'Ausfallschritt-Stretch', missing, 'Ausfallschritt-Stretch'),
  exercise('open-book', 'Open Book', 'Mobility', 'BWS-Rotation zur Entlastung der HWS', 'Die Rotation kommt aus der Brustwirbelsäule.', 'Endpositionen erzwingen.'),
  exercise('chin-tucks', 'Chin Tucks', 'Nacken/HWS', 'Tiefe Nackenmuskulatur und Kopfposition', 'Doppelkinn machen; klein und ruhig, nicht nach unten nicken.', 'Nach unten nicken oder in Schmerz hineinarbeiten.', '5 langsame Wiederholungen in der akuten Phase.', '2 × 8, je 3 Sekunden halten.'),
  exercise('dead-bug', 'Dead Bug', 'Core', 'Rumpfkontrolle; erste Wahl bei LWS-Sensibilität', 'Kontrolliert ausführen.', 'Mit vorgeschobenem Kopf arbeiten.', 'Bird Dog', missing, 'Bird Dog oder Pallof Press'),
  exercise('bird-dog', 'Bird Dog', 'Core', 'Rumpfkontrolle', 'Kontrolliert ausführen.', 'Endpositionen erzwingen.', 'Dead Bug', missing, 'Dead Bug'),
  exercise('head-rotation', 'Kontrollierte Kopfrotation', 'Nacken/HWS', 'Rotation zurückgewinnen, ohne zu forcieren', 'Nur im angenehmen Bereich drehen.', 'Rotation forcieren oder ruckartig dehnen.', 'Kleinere Bewegung in angenehmem Bereich.'),
  exercise('wall-slides', 'Wall Slides', 'Schultern', 'Schulterblattkontrolle und obere Rückenkette', 'Kontrolliert und ruhig ausführen.', 'Schultern hochziehen.'),
  exercise('neck-isometric-side', 'Nacken-Isometrie seitlich', 'Nacken/HWS', 'Belastbarkeit gegen Seitneigung', '3 × 5 Sekunden pro Seite.', 'Ruckartig drücken.'),
  exercise('neck-isometric-front-back', 'Nacken-Isometrie vorne/hinten', 'Nacken/HWS', 'Kontrollierte HWS-Stabilität', 'Vorne und hinten jeweils 3 × 5 Sekunden.', 'Ruckartig drücken.'),
  exercise('bike', 'Bike', 'Beine', 'Lockere Durchblutung und optionales Cardio', 'Locker fahren.', 'Bei gereiztem Rücken oder Knie Vollgas geben.', 'Lockeres Gehen.'),
  exercise('treadmill-walk', 'Laufband-Gehen', 'Beine', 'Lockere Durchblutung', 'Locker gehen.', 'Bei gereiztem Rücken, Knie oder Nacken Joggen erzwingen.', 'Gehen.'),
  exercise('walk', 'Gehen', 'Mobility', 'Durchblutung und Spannung reduzieren', 'Locker 5–15 Minuten gehen.'),
  exercise('knee-to-wall', 'Knie-vor-Wand', 'Knie', 'Sprunggelenksmobilität für bessere Kniekontrolle', 'Sauber und kontrolliert ausführen.', 'Bei Schmerz 4+/10 fortfahren.', 'Bewegungsradius bei Schmerz 3/10 reduzieren.'),
  exercise('tke', 'Terminal Knee Extensions', 'Knie', 'Quadrizeps aktivieren und Endstreckung trainieren', 'Kontrolliert ausführen.'),
  exercise('glute-bridge', 'Glute Bridge', 'Beine', 'Gesäß und Hüfte aktivieren', 'Keine LWS-Überstreckung.', 'LWS überstrecken.', missing, 'Hip Thrust', 'Hip Thrust oder Glute Bridge Maschine'),
  exercise('chest-press', 'Brustpresse', 'Brust', 'Brusttraining', 'Normal bis moderat und sauber; Kopf und Schultern stabil.', 'Kopf oder Schultern instabil werden lassen.', 'Kabel-Brustdrücken', 'Schrägbankdrücken', 'Schrägbankdrücken oder Kabel-Brustdrücken'),
  exercise('incline-press', 'Schrägbankdrücken', 'Brust', 'Brusttraining', 'Normal bis moderat und sauber.', missing, 'Brustpresse', missing, 'Brustpresse'),
  exercise('cable-chest-press', 'Kabel-Brustdrücken', 'Brust', 'Brusttraining', 'Kopf und Schultern stabil halten.', missing, 'Brustpresse', missing, 'Brustpresse'),
  exercise('lat-pulldown', 'Latzug neutral/eng', 'Rücken', 'Rückentraining', 'Neutralen oder engen Griff verwenden.', 'HWS beziehungsweise Schultern hochziehen.'),
  exercise('leg-press', 'Beinpresse beidbeinig', 'Beine', 'Moderater Beinanteil', 'Leicht bis moderat und beidbeinig ausführen.', 'Einbeinige Beinpresse verwenden.', 'Gewicht oder Bewegungsradius reduzieren.', missing, 'Step-ups niedrig'),
  exercise('chest-supported-row', 'Brustgestütztes Rudern', 'Rücken', 'Rücken- und nackenfreundliches Rudern', 'Brustgestützt und kontrolliert rudern.', 'Freies schweres Rudern bei Nackenreiz.', missing, missing, 'Statt freiem Rudern verwenden.'),
  exercise('leg-curl', 'Beinbeuger', 'Beine', 'Ersatz für RDL in der aktuellen Phase', 'Kontrolliert ausführen.', missing, missing, 'RDL erst nach erfolgreichem Re-Entry.', 'RDL-Ersatz zusammen mit Hip Thrust oder Glute Bridge'),
  exercise('lateral-raise', 'Seitheben', 'Schultern', 'Schultertraining', 'Leicht bis moderat, langsam; Schulterblätter kontrollieren.', 'Schwer mit hochgezogenen Schultern ausführen.', 'Leichter und langsamer ausführen.'),
  exercise('biceps-curl', 'Bizepscurls', 'Arme', 'Bizepstraining', 'Kontrolliert ausführen.', missing, 'Hammercurls', missing, 'Hammercurls'),
  exercise('triceps-pushdown', 'Trizeps Pushdowns', 'Arme', 'Trizepstraining', 'Kontrolliert ausführen.', missing, missing, 'Trizepsseil über Kopf bei ruhigem Nacken.', 'Bei Nackenstress statt Überkopf-Trizeps verwenden.'),
  exercise('pallof-press', 'Pallof Press', 'Core', 'Anti-Rotation und Rumpfstabilität', 'Kontrolliert ausführen.', missing, 'Dead Bug', missing, 'Dead Bug'),
  exercise('calf-raise', 'Wadenheben', 'Beine', 'Knie- und Sprunggelenkskette', 'Kontrolliert ausführen.'),
  exercise('hip-flexor-quad-stretch', 'Hüftbeuger-/Quad-Stretch', 'Mobility', 'Sanfter Abschluss', '30–45 Sekunden pro Seite, nur sanft.', 'Dehnung erzwingen.'),
  exercise('monster-walk', 'Monster Walks leicht', 'Beine', 'Beinachse und Hüfte', 'Leicht und kontrolliert ausführen.'),
  exercise('step-up', 'Step-ups niedrig', 'Knie', 'Beintraining mit Priorität für das linke Knie', 'Niedrige Höhe verwenden und langsam ausführen.', 'Zu schnell oder unkontrolliert arbeiten.', 'Bewegungsradius reduzieren.', missing, 'Beidbeinige Beinpresse'),
  exercise('landmine-press', 'Landmine Press', 'Schultern', 'Schultertraining mit reduzierter Nackenbelastung', 'Bei Nackenreiz sehr leicht ausführen oder auslassen.', 'Bei Nackenreiz schwer drücken.', 'Auslassen.', 'Schulterpresse leicht bei ruhigem Nacken.', 'Schulterpresse leicht'),
  exercise('shoulder-press-light', 'Schulterpresse leicht', 'Schultern', 'Schultertraining', 'Nur leicht; bei Nackenreiz auslassen.', 'Schweres Schulterdrücken bei Nackenreiz.', 'Landmine Press sehr leicht oder auslassen.', missing, 'Landmine Press'),
  exercise('hip-thrust', 'Hip Thrust', 'Beine', 'Gesäß und Hüfte trainieren', 'Keine LWS-Überstreckung.', 'LWS überstrecken.', 'Glute Bridge Maschine', missing, 'Glute Bridge Maschine'),
  exercise('glute-bridge-machine', 'Glute Bridge Maschine', 'Beine', 'Gesäß und Hüfte trainieren', 'Keine LWS-Überstreckung.', 'LWS überstrecken.', 'Glute Bridge', 'Hip Thrust', 'Hip Thrust'),
  exercise('reverse-fly', 'Reverse Fly', 'Schultern', 'Hintere Schulter und Schulterblattführung', 'Leicht ausführen und Schulterblätter führen.', 'Schultern hochziehen.', 'Face Pulls', missing, 'Face Pulls'),
  exercise('face-pulls', 'Face Pulls', 'Schultern', 'Schulterblattführung', 'Leicht ausführen und Schulterblätter führen.', 'Schultern hochziehen.', 'Reverse Fly', missing, 'Reverse Fly'),
  exercise('hammer-curl', 'Hammercurls', 'Arme', 'Armtraining', 'Kontrolliert ausführen.', missing, 'Bizepscurls', missing, 'Bizepscurls'),
  exercise('overhead-triceps', 'Trizepsseil über Kopf', 'Arme', 'Trizepstraining', 'Nur verwenden, wenn der Nacken ruhig bleibt.', 'Bei Nackenstress über Kopf trainieren.', 'Trizeps Pushdowns', missing, 'Trizeps Pushdowns'),
  exercise('side-plank', 'Side Plank kurz', 'Core', 'Rumpfstabilität', 'Nur ausführen, wenn der Nacken neutral bleibt.', 'Mit vorgeschobenem Kopf arbeiten.', 'Dead Bug', missing, 'Dead Bug oder Pallof Press'),
  exercise('single-leg-stand', 'Einbeinstand', 'Knie', 'Stabilität und Propriozeption', 'Kontrolliert 30–45 Sekunden pro Seite.', missing, missing, missing, 'Step-down niedrig'),
  exercise('step-down', 'Step-down niedrig', 'Knie', 'Kontrollierte Knieachse', 'Niedrige Höhe und kontrollierte Knieachse.', 'Bei Schmerz 4+/10 fortfahren.', 'Bewegungsradius reduzieren.', 'Step-ups niedrig', 'Step-ups niedrig'),
  exercise('side-bend', 'Seitneigung', 'Nacken/HWS', 'Sanfte Bewegung in der akuten Nackenphase', 'Nur im angenehmen Bereich.', 'Mit der Hand nachziehen.'),
  exercise('shoulder-blades', 'Schulterblätter hinten-unten', 'Nacken/HWS', 'Spannung reduzieren', 'Locker nach hinten-unten bewegen, ohne zu pressen.', 'Pressen oder Schultern hochziehen.'),
  exercise('rdl', 'Rumänisches Kreuzheben', 'Rücken', 'Späterer defensiver Hip-Hinge-Re-Entry', 'Vorerst 2–3 Wochen pausieren. Re-Entry erst, wenn der untere Rücken nach Trainingstagen ruhig bleibt.', 'In der aktuellen Phase normal oder schwer einsteigen.', 'Stufe 1: 2 × 8 sehr leicht mit verkürztem Bewegungsradius.', 'Stufe 3: 2–3 × 8 moderat, nur wenn die LWS 24 Stunden ruhig bleibt.', 'Beinbeuger plus Hip Thrust oder Glute Bridge'),
  exercise('walk-jog', 'Walk/Jog', 'Beine', 'Defensiver Laufaufbau', 'Mit Geh-/Jog-Intervallen der passenden Phase arbeiten.', 'Bei gereiztem Rücken, Knie oder Nacken Joggen erzwingen.', 'Lockeres Gehen oder Bike.'),
  exercise('leg-extension', 'Beinstrecker', 'Beine', 'Quadrizeps-Krafttraining', 'Kontrolliert ausführen.'),
  exercise('calf-raise-leg-press', 'Wadenheben an der Beinpresse', 'Beine', 'Eigenständiges Wadentraining an der Beinpresse', 'Als eigene Übung mit eigenen Sätzen und Gewichten ausführen.'),
  exercise('incline-chest-press-machine', 'Schrägbrustpresse Maschine', 'Brust', 'Brusttraining an der Maschine', 'Schulterblätter stabil halten und kontrolliert drücken.'),
  exercise('barbell-bench-press', 'Bankdrücken Langhantel', 'Brust', 'Horizontales Brustdrücken', 'Füße stabil, Schulterblätter kontrolliert und Stange sauber führen.'),
  exercise('barbell-incline-bench-press', 'Schrägbankdrücken Langhantel', 'Brust', 'Oberer Brustanteil', 'Moderate Bankneigung und kontrollierte Stangenführung.'),
  exercise('dumbbell-bench-press', 'Kurzhantel-Bankdrücken', 'Brust', 'Horizontales Brustdrücken mit Kurzhanteln', 'Kurzhanteln kontrolliert und symmetrisch führen.'),
  exercise('dumbbell-incline-bench-press', 'Kurzhantel-Schrägbankdrücken', 'Brust', 'Oberer Brustanteil mit Kurzhanteln', 'Moderate Bankneigung und stabile Schulterposition.'),
  exercise('cable-fly', 'Cable Flys', 'Brust', 'Brustadduktion am Kabel', 'Leichte Ellenbogenbeugung halten und kontrolliert zusammenführen.'),
  exercise('pec-deck', 'Butterfly / Pec Deck', 'Brust', 'Geführte Brustadduktion', 'Schulterblätter stabil halten und nicht ins Gelenk ziehen.'),
  exercise('push-up', 'Liegestütze', 'Brust', 'Brust, Trizeps und Rumpf', 'Körperlinie stabil halten und kontrolliert absenken.'),
  exercise('dips', 'Dips', 'Brust', 'Brust und Trizeps', 'Nur in einem schmerzfreien Schulterbereich arbeiten.'),
  exercise('assisted-dip-machine', 'Dips-Maschine', 'Brust', 'Unterstützte Dips für Brust und Trizeps', 'Unterstützung so wählen, dass die Bewegung kontrolliert bleibt.'),
  exercise('lat-pulldown-wide', 'Latzug breit', 'Rücken', 'Vertikales Ziehen mit breitem Griff', 'Stange kontrolliert zur oberen Brust führen und Schultern tief halten.'),
  exercise('single-arm-lat-pulldown', 'Einarmiger Latzug', 'Rücken', 'Unilaterales vertikales Ziehen', 'Rumpf stabil halten und Schulter nicht hochziehen.'),
  exercise('pull-up', 'Klimmzüge', 'Rücken', 'Vertikales Ziehen mit Körpergewicht', 'Kontrolliert aus dem Rücken ziehen und nicht schwingen.'),
  exercise('assisted-pull-up', 'Unterstützte Klimmzüge', 'Rücken', 'Unterstütztes vertikales Ziehen', 'Unterstützung so wählen, dass volle Kontrolle möglich bleibt.'),
  exercise('cable-row', 'Kabelrudern', 'Rücken', 'Horizontales Ziehen am Kabel', 'Brust aufrecht halten und Ellenbogen kontrolliert zurückführen.'),
  exercise('machine-row', 'Rudern Maschine', 'Rücken', 'Geführtes horizontales Ziehen', 'Schultern tief halten und nicht ins Hohlkreuz ausweichen.'),
  exercise('one-arm-dumbbell-row', 'Einarmiges Kurzhantelrudern', 'Rücken', 'Unilaterales horizontales Ziehen', 'Rumpf stabil halten und Kurzhantel kontrolliert führen.'),
  exercise('t-bar-row', 'T-Bar Row', 'Rücken', 'Schweres horizontales Ziehen', 'Rückenposition stabil halten und ohne Schwung rudern.'),
  exercise('pullover-machine', 'Pullover Maschine', 'Rücken', 'Latissimus in Schulterextension', 'Rippen kontrollieren und Bewegung aus Schulter und Rücken führen.'),
  exercise('straight-arm-pulldown', 'Straight-Arm Pulldown', 'Rücken', 'Latissimus am Kabel isolieren', 'Arme nahezu gestreckt halten und Rumpf nicht mitschwingen lassen.'),
  exercise('hack-squat', 'Hack Squat', 'Beine', 'Geführte Kniebeuge für Quadrizeps und Gesäß', 'Fußposition stabil und Bewegungsradius kontrolliert wählen.'),
  exercise('back-squat', 'Kniebeuge', 'Beine', 'Quadrizeps, Gesäß und Rumpf', 'Rumpf stabil halten und Knie kontrolliert über die Füße führen.'),
  exercise('goblet-squat', 'Goblet Squat', 'Beine', 'Kniebeuge mit frontaler Last', 'Gewicht nah am Körper und Rumpf aufrecht halten.'),
  exercise('bulgarian-split-squat', 'Bulgarian Split Squat', 'Beine', 'Unilaterales Training für Quadrizeps und Gesäß', 'Hinteren Fuß erhöht ablegen, vorderes Knie kontrolliert führen und Becken stabil halten.'),
  exercise('split-squat', 'Split Squat', 'Beine', 'Unilaterales Beintraining', 'Stabiler Ausfallschrittstand und kontrollierte Auf- und Abbewegung.'),
  exercise('reverse-lunge', 'Reverse Lunges', 'Beine', 'Unilaterales Bein- und Gesäßtraining', 'Kontrolliert nach hinten steigen und vorderes Bein stabil halten.'),
  exercise('walking-lunge', 'Walking Lunges', 'Beine', 'Dynamisches unilaterales Beintraining', 'Schrittlänge kontrollieren und Becken stabil halten.'),
  exercise('seated-leg-curl', 'Beinbeuger sitzend', 'Beine', 'Kniebeugung und hintere Oberschenkel', 'Polster sauber einstellen und kontrolliert beugen.'),
  exercise('lying-leg-curl', 'Beinbeuger liegend', 'Beine', 'Kniebeugung und hintere Oberschenkel', 'Becken stabil halten und kontrolliert beugen.'),
  exercise('deadlift', 'Kreuzheben', 'Rücken', 'Ganzkörper-Hip-Hinge', 'Nur mit stabiler Rückenposition und passender Belastbarkeit ausführen.'),
  exercise('back-extension', 'Back Extension', 'Rücken', 'Hintere Kette und Rumpfstreckung', 'Aus Hüfte bewegen und LWS nicht überstrecken.'),
  exercise('cable-pull-through', 'Cable Pull Through', 'Beine', 'Gesäß und hintere Kette', 'Hüfte kontrolliert nach hinten führen und über das Gesäß strecken.'),
  exercise('cable-glute-kickback', 'Kickbacks am Kabel', 'Beine', 'Unilaterales Gesäßtraining', 'Becken stabil halten und Bein kontrolliert nach hinten führen.'),
  exercise('standing-calf-raise', 'Stehendes Wadenheben', 'Beine', 'Wadentraining mit gestrecktem Knie', 'Vollen kontrollierten Bewegungsradius verwenden.'),
  exercise('seated-calf-raise', 'Sitzendes Wadenheben', 'Beine', 'Soleus-orientiertes Wadentraining', 'Fersen kontrolliert absenken und vollständig anheben.'),
  exercise('single-leg-calf-raise', 'Einbeiniges Wadenheben', 'Beine', 'Unilaterales Wadentraining', 'Balance sichern und jede Seite getrennt protokollieren.'),
  exercise('machine-shoulder-press', 'Schulterpresse Maschine', 'Schultern', 'Geführtes Schulterdrücken', 'Kopf und Schulterblätter stabil halten.'),
  exercise('dumbbell-shoulder-press', 'Kurzhantel-Schulterdrücken', 'Schultern', 'Freies Schulterdrücken', 'Rumpf stabil halten und Kurzhanteln kontrolliert führen.'),
  exercise('dumbbell-lateral-raise', 'Seitheben Kurzhantel', 'Schultern', 'Seitliche Schulter', 'Leicht und kontrolliert heben, ohne die Schultern hochzuziehen.'),
  exercise('cable-lateral-raise', 'Seitheben Kabel', 'Schultern', 'Seitliche Schulter mit konstanter Spannung', 'Kabel kontrolliert führen und Rumpf ruhig halten.'),
  exercise('machine-lateral-raise', 'Seitheben Maschine', 'Schultern', 'Geführtes Training der seitlichen Schulter', 'Sitz und Polster passend einstellen und kontrolliert heben.'),
  exercise('front-raise', 'Frontheben', 'Schultern', 'Vordere Schulter', 'Leicht und kontrolliert bis ungefähr Schulterhöhe heben.'),
  exercise('machine-reverse-fly', 'Reverse Fly Maschine', 'Schultern', 'Hintere Schulter und Schulterblattführung', 'Brust stabil halten und Arme kontrolliert nach außen führen.'),
  exercise('cable-reverse-fly', 'Reverse Fly Kabel', 'Schultern', 'Hintere Schulter am Kabel', 'Leicht trainieren und Schulterblätter kontrollieren.'),
  exercise('dumbbell-curl', 'Kurzhantelcurls', 'Arme', 'Bizepstraining mit Kurzhanteln', 'Ellenbogen ruhig halten und kontrolliert beugen.'),
  exercise('barbell-curl', 'Langhantelcurls', 'Arme', 'Bizepstraining mit Langhantel', 'Rumpf ruhig halten und nicht aus der Hüfte schwingen.'),
  exercise('ez-bar-curl', 'SZ-Curls', 'Arme', 'Bizepstraining mit SZ-Stange', 'Handgelenke neutral und Ellenbogen stabil halten.'),
  exercise('cable-curl', 'Kabelcurls', 'Arme', 'Bizepstraining mit konstanter Spannung', 'Ellenbogen stabil halten und kontrolliert beugen.'),
  exercise('preacher-curl', 'Preacher Curls', 'Arme', 'Geführtes Bizepstraining', 'Oberarme auflegen und die untere Position nicht erzwingen.'),
  exercise('incline-dumbbell-curl', 'Incline Dumbbell Curls', 'Arme', 'Bizepstraining in verlängerter Position', 'Schultern stabil und Oberarme ruhig halten.'),
  exercise('rope-pushdown', 'Rope Pushdown', 'Arme', 'Trizepstraining am Seil', 'Ellenbogen am Körper halten und unten kontrolliert spreizen.'),
  exercise('single-arm-cable-pushdown', 'Einarmiger Kabel-Pushdown', 'Arme', 'Unilaterales Trizepstraining', 'Oberarm ruhig halten und jede Seite getrennt trainieren.'),
  exercise('skull-crusher', 'Skull Crushers', 'Arme', 'Trizepstraining in Ellenbogenbeugung', 'Oberarme stabil halten und Gewicht kontrolliert absenken.'),
  exercise('triceps-machine', 'Trizepsmaschine', 'Arme', 'Geführtes Trizepstraining', 'Sitz einstellen und Ellenbogen kontrolliert strecken.'),
  exercise('plank', 'Plank', 'Core', 'Rumpfspannung in neutraler Position', 'Kopf, Brustkorb und Becken stabil ausrichten.'),
  exercise('cable-crunch', 'Cable Crunch', 'Core', 'Belastete Rumpfbeugung', 'Wirbelsäule kontrolliert beugen und nicht aus der Hüfte ziehen.'),
  exercise('crunch-machine', 'Crunch Maschine', 'Core', 'Geführte belastete Rumpfbeugung', 'Gerät passend einstellen und kontrolliert beugen.'),
  exercise('hanging-knee-raise', 'Hanging Knee Raise', 'Core', 'Unterer Bauch und Hüftkontrolle', 'Becken kontrolliert einrollen und nicht schwingen.'),
  exercise('hanging-leg-raise', 'Hanging Leg Raise', 'Core', 'Fortgeschrittene Rumpf- und Hüftkontrolle', 'Nur mit kontrolliertem Becken und ohne Schwung ausführen.'),
  exercise('ab-wheel', 'Ab Wheel', 'Core', 'Anti-Extension und Rumpfspannung', 'Nur so weit rollen, wie die Rumpfposition stabil bleibt.'),
  exercise('farmer-carry', 'Farmer Carry', 'Core', 'Rumpf, Griffkraft und belastetes Gehen', 'Aufrecht und gleichmäßig gehen, ohne seitlich auszuweichen.'),
  exercise('knee-to-wall-pause', 'Knie-vor-Wand mit Pause', 'Mobility', 'Warm-up für Training A', 'Kontrolliert ausführen und kurz pausieren.'),
  exercise('adductor-rockback', 'Adductor Rockback', 'Mobility', 'Warm-up für Training A'),
  exercise('active-hip-switches', 'Aktive 90/90 Hip Switches', 'Mobility', 'Aktive Hüftrotation im Warm-up', 'Kontrolliert und aktiv ausführen.'),
  exercise('glute-bridge-march', 'Glute Bridge March', 'Core', 'Warm-up für Gesäß, Hüfte und Rumpf', 'Kontrolliert ausführen und die Körperposition stabil halten.'),
  exercise('thoracic-rotation-quadruped', 'Thoracic Rotation im Vierfüßler', 'Mobility', 'Brustwirbelsäulen-Rotation im Warm-up'),
  exercise('chin-tuck-rotation', 'Chin Tuck + Rotation', 'Nacken/HWS', 'Kopfposition und kontrollierte Rotation im Warm-up', 'Klein und kontrolliert ausführen.'),
  exercise('soleus-knee-to-wall', 'Knee-to-Wall / Soleus-Mobilisation', 'Mobility', 'Warm-up für Training B'),
  exercise('hip-liftoff', '90/90 Lift-off', 'Mobility', 'Aktive Hüftrotation im Warm-up', 'Kontrolliert ausführen.', missing, 'Aktive Hüftrotation', missing, 'Aktive 90/90 Hip Switches'),
  exercise('wall-slide-liftoff', 'Wall Slide mit Lift-off', 'Schultern', 'Schulter-Warm-up für Training B', 'Kontrolliert ausführen.'),
  exercise('calf-soleus-stretch', 'Wade-/Soleus-Mobilität', 'Mobility', 'Optionaler kurzer Cool-down'),
  exercise('chest-shoulder-mobility', 'Brust-/Schultermobilität', 'Mobility', 'Optionaler kurzer Cool-down'),
]

export const exerciseById = new Map(exercises.map((item) => [item.id, item]))

const step = (exerciseId: string, prescription: string, note: string, targetSets = 1): RoutineStep => ({ exerciseId, prescription, note, targetSets })

const templateStep = (
  templateExerciseId: string,
  section: WorkoutSection,
  exerciseId: string,
  prescription: string,
  note: string,
  targetSets = 1,
  restSeconds = 150,
): RoutineStep => ({ templateExerciseId, section, exerciseId, prescription, note, targetSets, restSeconds })

export const planUnits: PlanUnit[] = [
  {
    id: 'training-a',
    name: 'Ganzkörpertraining A',
    shortName: 'Training A',
    kind: 'strength',
    description: 'Brust-/Latzug-Fokus mit eigenständigem Bein-, Waden-, Arm- und Core-Training.',
    frequency: '1× pro Woche',
    steps: [
      templateStep('a-warmup-knee-wall', 'warmup', 'knee-to-wall-pause', '8 pro Seite', 'Kontrolliert, mit kurzer Pause'),
      templateStep('a-warmup-adductor', 'warmup', 'adductor-rockback', '6–8 pro Seite', 'Kontrollierter Warm-up'),
      templateStep('a-warmup-9090', 'warmup', 'active-hip-switches', '6 pro Seite', 'Aktive Hüftrotation'),
      templateStep('a-warmup-bridge-march', 'warmup', 'glute-bridge-march', '8 pro Seite', 'Position stabil halten'),
      templateStep('a-warmup-thoracic', 'warmup', 'thoracic-rotation-quadruped', '6 pro Seite', 'Kontrollierte BWS-Rotation'),
      templateStep('a-warmup-neck', 'warmup', 'chin-tuck-rotation', '5 pro Seite', 'Klein und kontrolliert'),
      templateStep('a-strength-chest', 'strength', 'chest-press', '3 × 8–10', 'Oder für heute durch Schrägbankdrücken ersetzen', 3),
      templateStep('a-strength-lat', 'strength', 'lat-pulldown', '3 × 8–10', 'Keine HWS hochziehen', 3),
      templateStep('a-strength-leg-press', 'strength', 'leg-press', '2–3 × 10–12', 'Beidbeinig, leicht-moderat', 2),
      templateStep('a-strength-leg-curl', 'strength', 'leg-curl', '2–3 × 10–12', 'Kontrolliert', 2),
      templateStep('a-strength-calf-press', 'strength', 'calf-raise-leg-press', '2–3 × 12–15', 'Eigenständig protokollieren', 2),
      templateStep('a-strength-lateral-raise', 'strength', 'lateral-raise', '2 × 12–15', 'Schultern nicht hochziehen', 2),
      templateStep('a-strength-biceps', 'strength', 'biceps-curl', '2 × 10–12', 'Kontrolliert', 2),
      templateStep('a-strength-triceps', 'strength', 'triceps-pushdown', '2 × 10–12', 'Kontrolliert', 2),
      templateStep('a-core-dead-bug', 'core', 'dead-bug', '2 × 8 pro Seite', 'Erste Wahl bei LWS-Sensibilität', 2),
      templateStep('a-core-pallof', 'core', 'pallof-press', '2 × 10 pro Seite', 'Anti-Rotation', 2),
      templateStep('a-cooldown-hip', 'cooldown', 'hip-flexor-quad-stretch', '30–45 Sekunden pro Seite', 'Optional und sanft'),
      templateStep('a-cooldown-open-book', 'cooldown', 'open-book', '5 pro Seite', 'Optional'),
      templateStep('a-cooldown-neck', 'cooldown', 'head-rotation', '5 pro Seite', 'Locker und kontrolliert'),
      templateStep('a-cooldown-calf', 'cooldown', 'calf-soleus-stretch', '30 Sekunden pro Seite', 'Optional'),
      templateStep('a-cooldown-chest', 'cooldown', 'chest-shoulder-mobility', '1–2 Minuten', 'Optional'),
    ],
  },
  {
    id: 'training-b',
    name: 'Ganzkörpertraining B',
    shortName: 'Training B',
    kind: 'strength',
    description: 'Step-ups, Rudern, Beinstrecker, hintere Schulter, Arme und Core.',
    frequency: '1× pro Woche',
    steps: [
      templateStep('b-warmup-soleus', 'warmup', 'soleus-knee-to-wall', '8 pro Seite', 'Kontrollierte Soleus-Mobilisation'),
      templateStep('b-warmup-step-down', 'warmup', 'step-down', '6 pro Seite', 'Niedrig und kontrolliert'),
      templateStep('b-warmup-hip', 'warmup', 'hip-liftoff', '5 pro Seite', 'Oder aktive Hüftrotation'),
      templateStep('b-warmup-monster', 'warmup', 'monster-walk', '10 Schritte pro Richtung', 'Leicht und kontrolliert'),
      templateStep('b-warmup-wall-slide', 'warmup', 'wall-slide-liftoff', '8 Wiederholungen', 'Kontrolliert'),
      templateStep('b-warmup-neck', 'warmup', 'head-rotation', '5 pro Seite', 'Nur angenehmer Bereich'),
      templateStep('b-strength-step-up', 'strength', 'step-up', '3 × 8 pro Seite', 'Niedrig und langsam', 3),
      templateStep('b-strength-chest', 'strength', 'chest-press', '3 × 8–10', 'Oder für heute durch Kabel-Brustdrücken ersetzen', 3),
      templateStep('b-strength-row', 'strength', 'chest-supported-row', '3 × 8–10', 'Rücken- und nackenfreundlich', 3),
      templateStep('b-strength-leg-extension', 'strength', 'leg-extension', '2 × 12–15', 'Dauerhafter Bestandteil', 2),
      templateStep('b-strength-hip-thrust', 'strength', 'hip-thrust', '2 × 10–12', 'Oder Glute Bridge Maschine', 2),
      templateStep('b-strength-reverse-fly', 'strength', 'reverse-fly', '2 × 12–15', 'Oder Face Pulls; primär hintere Schulter', 2),
      templateStep('b-strength-biceps', 'strength', 'hammer-curl', '2 × 10–12', 'Bizeps / Hammercurls', 2),
      templateStep('b-strength-triceps', 'strength', 'triceps-pushdown', '2 × 10–12', 'Bei Nackenreiz Pushdowns', 2),
      templateStep('b-core-side-plank', 'core', 'side-plank', '2 × 20–30 Sekunden pro Seite', 'Nur bei neutralem Nacken', 2),
      templateStep('b-core-dead-bug', 'core', 'dead-bug', '2 × 8 pro Seite', 'Alternative bei Nacken-/LWS-Reiz', 2),
      templateStep('b-cooldown-hip', 'cooldown', 'hip-flexor-quad-stretch', '30–45 Sekunden pro Seite', 'Optional und sanft'),
      templateStep('b-cooldown-open-book', 'cooldown', 'open-book', '5 pro Seite', 'Optional'),
      templateStep('b-cooldown-neck', 'cooldown', 'head-rotation', '5 pro Seite', 'Locker und kontrolliert'),
      templateStep('b-cooldown-calf', 'cooldown', 'calf-soleus-stretch', '30 Sekunden pro Seite', 'Optional'),
      templateStep('b-cooldown-chest', 'cooldown', 'chest-shoulder-mobility', '1–2 Minuten', 'Optional'),
    ],
  },
  {
    id: 'mobility',
    name: 'Tägliche Mobility-Routine',
    shortName: 'Mobility',
    kind: 'routine',
    description: 'Kurzer täglicher Basisreiz für Wirbelsäule, Hüfte, Core und Nacken.',
    frequency: 'Täglich',
    steps: [
      step('cat-cow', '1 Minute', 'Kleiner bis mittlerer Bewegungsradius'),
      step('hip-switches', '2 Minuten', 'Kontrolliert, nicht erzwingen'),
      step('lunge-stretch', '2 Minuten', 'Oder Couch Stretch; sanft, keine LWS-Überstreckung'),
      step('open-book', '1,5 Minuten', 'Rotation aus der Brustwirbelsäule'),
      step('chin-tucks', '1 Minute', 'Doppelkinn, nicht nach unten nicken'),
      step('dead-bug', '2,5 Minuten', 'Oder Bird Dog; nur eine Core-Übung wählen'),
    ],
  },
  {
    id: 'knee',
    name: 'Knie-Routine',
    shortName: 'Knie',
    kind: 'routine',
    description: 'Sprunggelenksmobilität, Quadrizeps, Knieachse und Stabilität.',
    frequency: 'Nach Bedarf / als Prehab',
    steps: [
      step('knee-to-wall', '10 pro Seite', 'Sprunggelenksmobilität'),
      step('tke', '2 × 15 pro Seite', 'Quadrizeps/Endstreckung', 2),
      step('step-down', '2 × 6–8 pro Seite', 'Kontrollierte Knieachse', 2),
      step('single-leg-stand', '30–45 Sekunden pro Seite', 'Stabilität/Propriozeption'),
    ],
  },
  {
    id: 'back',
    name: 'Rücken-Routine',
    shortName: 'Rücken',
    kind: 'routine',
    description: 'Sanfte Elemente aus Mobility und Rückensteuerung; RDL bleibt vorerst pausiert.',
    frequency: 'Bei Bedarf',
    steps: [
      step('cat-cow', '1 Minute', 'Kleiner bis mittlerer Bewegungsradius'),
      step('open-book', '1 × 6 pro Seite', 'BWS-Rotation'),
      step('dead-bug', '2 × 8 pro Seite', 'Erste Wahl bei LWS-Sensibilität', 2),
      step('bird-dog', '2 × 6 pro Seite', 'Rumpfkontrolle', 2),
      step('walk', '5–15 Minuten', 'Durchblutung, Spannung reduzieren'),
    ],
  },
  {
    id: 'neck',
    name: 'Nacken-/HWS-Routine',
    shortName: 'Nacken/HWS',
    kind: 'routine',
    description: 'Sanfter Block für Kopfposition, Rotation, Schulterblattkontrolle und HWS-Stabilität.',
    frequency: '4–6× pro Woche',
    steps: [
      step('chin-tucks', '2 × 8, je 3 Sekunden', 'Tiefe Nackenmuskulatur', 2),
      step('head-rotation', '1 × 6 pro Seite', 'Ohne zu forcieren'),
      step('open-book', '1 × 6 pro Seite', 'BWS-Rotation entlastet HWS'),
      step('wall-slides', '2 × 8', 'Schulterblattkontrolle', 2),
      step('neck-isometric-side', '3 × 5 Sekunden pro Seite', 'Belastbarkeit gegen Seitneigung', 3),
      step('neck-isometric-front-back', 'Je 3 × 5 Sekunden', 'Kontrollierte HWS-Stabilität', 3),
    ],
  },
  {
    id: 'cardio',
    name: 'Cardio / Laufaufbau',
    shortName: 'Cardio',
    kind: 'routine',
    description: 'Defensiver Walk-/Jog-Aufbau oder Bike, nur bei ruhigem Rücken und Knie.',
    frequency: 'Optional 1× pro Woche',
    steps: [
      step('walk-jog', 'Woche 1–2: 5 Min gehen, 1 Min locker joggen, 4 Min gehen – 5 Wiederholungen', 'Nur schmerzfrei wiederholen'),
      step('walk-jog', 'Woche 3–4: 4 Min gehen, 2 Min joggen – 5 Wiederholungen', 'Kein Rücken-/Knieanstieg am Folgetag'),
      step('walk-jog', 'Woche 5–6: 3 Min gehen, 3 Min joggen – 5 Wiederholungen', 'Stabile Technik'),
      step('walk-jog', 'Woche 7–8: 2 Min gehen, 5 Min joggen – 4 Wiederholungen', 'Erst danach Richtung 30 Min durchlaufen'),
    ],
  },
]

export const freeWorkoutTemplate: PlanUnit = {
  id: 'free-training',
  name: 'Freie Einheit',
  shortName: 'Freies Training',
  kind: 'strength',
  description: 'Leere Session, die du für heute frei mit Kraftübungen zusammenstellst.',
  frequency: 'Jederzeit',
  steps: [],
}

export const unitById = new Map([...planUnits, freeWorkoutTemplate].map((unit) => [unit.id, unit]))

export const strengthExerciseIds = new Set([
  'chest-press',
  'incline-press',
  'cable-chest-press',
  'lat-pulldown',
  'leg-press',
  'chest-supported-row',
  'leg-curl',
  'leg-extension',
  'calf-raise',
  'calf-raise-leg-press',
  'lateral-raise',
  'biceps-curl',
  'hammer-curl',
  'triceps-pushdown',
  'overhead-triceps',
  'step-up',
  'landmine-press',
  'shoulder-press-light',
  'hip-thrust',
  'glute-bridge-machine',
  'reverse-fly',
  'face-pulls',
  'rdl',
  'incline-chest-press-machine',
  'barbell-bench-press',
  'barbell-incline-bench-press',
  'dumbbell-bench-press',
  'dumbbell-incline-bench-press',
  'cable-fly',
  'pec-deck',
  'push-up',
  'dips',
  'assisted-dip-machine',
  'lat-pulldown-wide',
  'single-arm-lat-pulldown',
  'pull-up',
  'assisted-pull-up',
  'cable-row',
  'machine-row',
  'one-arm-dumbbell-row',
  't-bar-row',
  'pullover-machine',
  'straight-arm-pulldown',
  'hack-squat',
  'back-squat',
  'goblet-squat',
  'bulgarian-split-squat',
  'split-squat',
  'reverse-lunge',
  'walking-lunge',
  'seated-leg-curl',
  'lying-leg-curl',
  'deadlift',
  'back-extension',
  'cable-pull-through',
  'cable-glute-kickback',
  'standing-calf-raise',
  'seated-calf-raise',
  'single-leg-calf-raise',
  'machine-shoulder-press',
  'dumbbell-shoulder-press',
  'dumbbell-lateral-raise',
  'cable-lateral-raise',
  'machine-lateral-raise',
  'front-raise',
  'machine-reverse-fly',
  'cable-reverse-fly',
  'dumbbell-curl',
  'barbell-curl',
  'ez-bar-curl',
  'cable-curl',
  'preacher-curl',
  'incline-dumbbell-curl',
  'rope-pushdown',
  'single-arm-cable-pushdown',
  'skull-crusher',
  'triceps-machine',
  'plank',
  'cable-crunch',
  'crunch-machine',
  'hanging-knee-raise',
  'hanging-leg-raise',
  'ab-wheel',
  'farmer-carry',
])

export const medicalNotice = 'Diese App ersetzt keine ärztliche oder physiotherapeutische Diagnose. Bei starken Schmerzen, Ausstrahlung, Taubheit, Kraftverlust oder deutlicher Verschlechterung sollte medizinisch abgeklärt werden, bevor weitertrainiert wird.'

export const neckWarning = 'Bei starker Bewegungseinschränkung, Ausstrahlung in Arm/Hand, Taubheit, Kraftverlust, Schwindel, Fieber, starken Kopfschmerzen oder Beschwerden nach Unfall: nicht wegtrainieren, sondern medizinisch abklären.'

export const painRules = [
  ['0–2/10', 'Trainieren, aber sauber und kontrolliert.'],
  ['3/10', 'Bewegungsradius oder Gewicht reduzieren.'],
  ['4+/10', 'Übung abbrechen und ersetzen.'],
  ['Schwellung, Wegknicken, Blockieren', 'Training stoppen und medizinisch/physiotherapeutisch abklären.'],
]
